//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int cart_id { get; set; }
        public Nullable<int> cart_fk_user { get; set; }
        public Nullable<int> cart_fk_product { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
        public virtual tbl_product tbl_product { get; set; }
    }
}
